branches: {only: [master]}

dist: xenial
sudo: false
cache: pip
language: python

matrix:
  include:
    - {env: TOXENV=style, python: "3.6"}
    - python: "3.6"
    - python: "3.7"

install:
  - pip install -U pip codecov setuptools tox-travis

script: tox -v

after_success: codecov -e TRAVIS_PYTHON_VERSION
